### ISSUE TITLE
Keystore and password in memory security issue

### ISSUE THREAD

**Issue by Spl3en** [paradigmcitadel/icon_voting#1]
https://github.com/paradigmcitadel/icon_voting/blob/b38c0274cc7650387975c8ac453db551f8d70fb3/src/containers/login/Login.jsx#L33-L34

Please reconsider keeping the wallet keystore+password in memory (which is the same than storing a plaintext private key in memory). Alternatively, you may want to educate the users about the risks of running such application.

**Comment by cybor97** [comment]
What about to store them encrypted with native OS API?
https://atom.github.io/node-keytar/

**Comment by cybor97** [comment]
> What about to store them encrypted with native OS API?
> https://atom.github.io/node-keytar/

Added storing in OS keychain
